In [1]:
import os
os.environ['TF_CPP_MIN_LOG_LEVEL'] = '3'
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import tensorflow as tf

In [2]:
data_path = '/home/hanlinn/00.projects/tensorflow-prepare/example-file/sign-mnist/sign_mnist_train.csv'
df = pd.read_csv(data_path)

In [3]:
df.head()

,label,pixel1,pixel2,pixel3,pixel4,pixel5,pixel6,pixel7,pixel8,pixel9,...,pixel775,pixel776,pixel777,pixel778,pixel779,pixel780,pixel781,pixel782,pixel783,pixel784
0,3,107,118,127,134,139,143,146,150,153,...,207,207,207,207,206,206,206,204,203,202
1,6,155,157,156,156,156,157,156,158,158,...,69,149,128,87,94,163,175,103,135,149
2,2,187,188,188,187,187,186,187,188,187,...,202,201,200,199,198,199,198,195,194,195
3,2,211,211,212,212,211,210,211,210,210,...,235,234,233,231,230,226,225,222,229,163
4,13,164,167,170,172,176,179,180,184,185,...,92,105,105,108,133,163,157,163,164,179

In [4]:
test_data_path = '/home/hanlinn/00.projects/tensorflow-prepare/example-file/sign-mnist/sign_mnist_test.csv'
test_df = pd.read_csv(test_data_path)
test_df.head()

,label,pixel1,pixel2,pixel3,pixel4,pixel5,pixel6,pixel7,pixel8,pixel9,...,pixel775,pixel776,pixel777,pixel778,pixel779,pixel780,pixel781,pixel782,pixel783,pixel784
0,6,149,149,150,150,150,151,151,150,151,...,138,148,127,89,82,96,106,112,120,107
1,5,126,128,131,132,133,134,135,135,136,...,47,104,194,183,186,184,184,184,182,180
2,10,85,88,92,96,105,123,135,143,147,...,68,166,242,227,230,227,226,225,224,222
3,0,203,205,207,206,207,209,210,209,210,...,154,248,247,248,253,236,230,240,253,255
4,3,188,191,193,195,199,201,202,203,203,...,26,40,64,48,29,46,49,46,46,53

In [5]:
train_label = df['label']
test_label = test_df['label']
del df['label']
del test_df['label']

In [6]:
from sklearn.preprocessing import LabelBinarizer
label_binarizer = LabelBinarizer()
train_label = label_binarizer.fit_transform(y=train_label)
test_label = label_binarizer.fit_transform(y=test_label)

In [7]:
df.head()

,pixel1,pixel2,pixel3,pixel4,pixel5,pixel6,pixel7,pixel8,pixel9,pixel10,...,pixel775,pixel776,pixel777,pixel778,pixel779,pixel780,pixel781,pixel782,pixel783,pixel784
0,107,118,127,134,139,143,146,150,153,156,...,207,207,207,207,206,206,206,204,203,202
1,155,157,156,156,156,157,156,158,158,157,...,69,149,128,87,94,163,175,103,135,149
2,187,188,188,187,187,186,187,188,187,186,...,202,201,200,199,198,199,198,195,194,195
3,211,211,212,212,211,210,211,210,210,211,...,235,234,233,231,230,226,225,222,229,163
4,164,167,170,172,176,179,180,184,185,186,...,92,105,105,108,133,163,157,163,164,179

In [8]:
test_df.head()

,pixel1,pixel2,pixel3,pixel4,pixel5,pixel6,pixel7,pixel8,pixel9,pixel10,...,pixel775,pixel776,pixel777,pixel778,pixel779,pixel780,pixel781,pixel782,pixel783,pixel784
0,149,149,150,150,150,151,151,150,151,152,...,138,148,127,89,82,96,106,112,120,107
1,126,128,131,132,133,134,135,135,136,138,...,47,104,194,183,186,184,184,184,182,180
2,85,88,92,96,105,123,135,143,147,152,...,68,166,242,227,230,227,226,225,224,222
3,203,205,207,206,207,209,210,209,210,209,...,154,248,247,248,253,236,230,240,253,255
4,188,191,193,195,199,201,202,203,203,203,...,26,40,64,48,29,46,49,46,46,53

In [9]:
train_feature = df.values
test_feature = test_df.values

In [11]:
train_label[1]

array([0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0])

In [12]:
train_feature.shape, test_feature.shape, train_label.shape, test_label.shape

((27455, 784), (7172, 784), (27455, 24), (7172, 24))

In [13]:
reshape_train = train_feature / 255
reshape_test = test_feature / 255

In [41]:
reshape_train = reshape_train.reshape(-1,28,28,1)
reshape_test = reshape_test.reshape(-1,28,28,1)

In [42]:
# Preprocess the data
# Turn our data into TensorFlow Datasets
train_dataset = tf.data.Dataset.from_tensor_slices((reshape_train, train_label))
train_dataset =  train_dataset.batch(32).prefetch(tf.data.AUTOTUNE)
valid_dataset = tf.data.Dataset.from_tensor_slices((reshape_test,test_label))
valid_dataset = valid_dataset.batch(32).prefetch(tf.data.AUTOTUNE)
print(f"Train : {train_dataset} \n"
      f"Test : {valid_dataset}")

Train : <PrefetchDataset element_spec=(TensorSpec(shape=(None, 28, 28, 1), dtype=tf.float64, name=None), TensorSpec(shape=(None, 24), dtype=tf.int64, name=None))>
Test : <PrefetchDataset element_spec=(TensorSpec(shape=(None, 28, 28, 1), dtype=tf.float64, name=None), TensorSpec(shape=(None, 24), dtype=tf.int64, name=None))>

In [43]:

# Callbacks
early_stopping = tf.keras.callbacks.EarlyStopping(monitor="val_loss", # watch the val loss metric
                                                  patience=5) # if val loss decreases for 3 epochs in a row, stop training

reduce_lr = tf.keras.callbacks.ReduceLROnPlateau(monitor="val_loss",  
                                                 factor=0.2, # multiply the learning rate by 0.2 (reduce by 5x)
                                                 patience=3,
                                                 verbose=1, # print out when learning rate goes down 
                                                 min_lr=1e-7)

In [46]:
from tensorflow.keras import layers
input_shape =(28,28,1)
#Build the model
inputs = layers.Input(shape=input_shape, name="input_layer")
x = layers.Conv2D(32, kernel_size=3, padding="same", activation="elu")(inputs)
# x = layers.Conv2D(32, kernel_size=3, padding="same", activation="elu")(x)
x = layers.BatchNormalization()(x)
x = layers.MaxPooling2D()(x)
x = layers.Dropout(0.1)(x)
x = layers.Conv2D(64, kernel_size=3, padding="same", activation="elu")(x)
# x = layers.Conv2D(64, kernel_size=3, padding="same", activation="elu")(x)
x = layers.BatchNormalization()(x)
x = layers.MaxPooling2D()(x)
x = layers.Dropout(0.25)(x)
x = layers.Conv2D(128, kernel_size=3, padding="same" ,activation="elu")(x)
# x = layers.Conv2D(128, kernel_size=3, padding="same",activation="elu")(x)
x = layers.BatchNormalization()(x)
x = layers.MaxPooling2D()(x)
x = layers.Dropout(0.5)(x)
x = layers.Flatten()(x)
x = layers.Dense(128, activation="elu", name="Dense_1")(x)
x = layers.Dropout(0.5)(x)
x = layers.Dense(64, activation="elu", name="Dense_2")(x)
outputs = layers.Dense(24, activation="softmax",name="output_layer")(x)      
model = tf.keras.Model(inputs, outputs) 

model.compile(loss="categorical_crossentropy",
              optimizer=tf.keras.optimizers.Adam(),
              metrics=["accuracy"])

model.summary()

Model: "model_3"
_________________________________________________________________
 Layer (type)                Output Shape              Param #
=================================================================
 input_layer (InputLayer)    [(None, 28, 28, 1)]       0

 conv2d_28 (Conv2D)          (None, 28, 28, 32)        320

 batch_normalization_10 (Bat  (None, 28, 28, 32)       128
 chNormalization)

 max_pooling2d_20 (MaxPoolin  (None, 14, 14, 32)       0
 g2D)

 dropout_12 (Dropout)        (None, 14, 14, 32)        0

 conv2d_29 (Conv2D)          (None, 14, 14, 64)        18496

 batch_normalization_11 (Bat  (None, 14, 14, 64)       256
 chNormalization)

 max_pooling2d_21 (MaxPoolin  (None, 7, 7, 64)         0
 g2D)

 dropout_13 (Dropout)        (None, 7, 7, 64)          0

 conv2d_30 (Conv2D)          (None, 7, 7, 128)         73856

 batch_normalization_12 (Bat  (None, 7, 7, 128)        512
 chNormalization)

 max_pooling2d_22 (MaxPoolin  (None, 3, 3, 128)        0
 g2D)

 dropout_14 (Dropout)        (None, 3, 3, 128)         0

 flatten_8 (Flatten)         (None, 1152)              0

 Dense_1 (Dense)             (None, 128)               147584

 dropout_15 (Dropout)        (None, 128)               0

 Dense_2 (Dense)             (None, 64)                8256

 output_layer (Dense)        (None, 24)                1560

=================================================================
Total params: 250,968
Trainable params: 250,520
Non-trainable params: 448
_________________________________________________________________

In [48]:
from datetime import datetime
epoch = 10
start = datetime.now()
history_model = model.fit(train_dataset,
                          steps_per_epoch=len(train_dataset),
                          validation_data=valid_dataset,
                          validation_steps=int(0.25*len(valid_dataset)),
                          callbacks=[early_stopping, reduce_lr],
                          epochs=epoch) 
end = datetime.now()

print(f"The time taken to train the model is {end - start}")
# Evaluate model
model.evaluate(valid_dataset)

Epoch 1/10
858/858 [==============================] - 24s 28ms/step - loss: 0.7182 - accuracy: 0.7543 - val_loss: 0.3090 - val_accuracy: 0.8862 - lr: 0.0010
Epoch 2/10
858/858 [==============================] - 22s 26ms/step - loss: 0.1783 - accuracy: 0.9401 - val_loss: 0.1366 - val_accuracy: 0.9548 - lr: 0.0010
Epoch 3/10
858/858 [==============================] - 25s 30ms/step - loss: 0.1027 - accuracy: 0.9646 - val_loss: 0.1284 - val_accuracy: 0.9632 - lr: 0.0010
Epoch 4/10
858/858 [==============================] - 24s 28ms/step - loss: 0.0836 - accuracy: 0.9728 - val_loss: 0.1134 - val_accuracy: 0.9632 - lr: 0.0010
Epoch 5/10
858/858 [==============================] - 18s 21ms/step - loss: 0.0630 - accuracy: 0.9791 - val_loss: 0.2075 - val_accuracy: 0.9587 - lr: 0.0010
Epoch 6/10
858/858 [==============================] - 20s 24ms/step - loss: 0.0603 - accuracy: 0.9805 - val_loss: 0.1082 - val_accuracy: 0.9715 - lr: 0.0010
Epoch 7/10
858/858 [==============================] - 23s 27ms/step - loss: 0.0542 - accuracy: 0.9829 - val_loss: 0.1735 - val_accuracy: 0.9648 - lr: 0.0010
Epoch 8/10
858/858 [==============================] - 24s 28ms/step - loss: 0.0566 - accuracy: 0.9837 - val_loss: 0.0957 - val_accuracy: 0.9749 - lr: 0.0010
Epoch 9/10
858/858 [==============================] - 26s 30ms/step - loss: 0.0368 - accuracy: 0.9881 - val_loss: 0.1573 - val_accuracy: 0.9682 - lr: 0.0010
Epoch 10/10
858/858 [==============================] - 26s 31ms/step - loss: 0.0456 - accuracy: 0.9867 - val_loss: 0.2713 - val_accuracy: 0.9626 - lr: 0.0010
The time taken to train the model is 0:03:53.530749
225/225 [==============================] - 2s 9ms/step - loss: 0.2182 - accuracy: 0.9667

[0.2181529700756073, 0.9666759371757507]

In [49]:

def calculate_accuracy_results(y_true, y_pred):
    from sklearn.metrics import accuracy_score, precision_recall_fscore_support
    """
     Calculates model accuracy, precision, recall and f1 score of a binary classification model.

    Args:
        y_true: true labels in the form of a 1D array
        y_pred: predicted labels in the form of a 1D array

    Returns a dictionary of accuracy, precision, recall, f1-score.
    """
    # Calculate model accuracy
    model_accuracy = accuracy_score(y_true, y_pred) * 100
    # Calculate model precision, recall and f1 score using "weighted average
    model_precision, model_recall, model_f1, _ = precision_recall_fscore_support(y_true, y_pred, average="weighted", zero_division= 1)
    model_results = {"accuracy": model_accuracy,
                      "precision": model_precision,
                      "recall": model_recall,
                      "f1": model_f1}
    return model_results

model_preds_probs = model.predict(reshape_test)
model_preds = tf.argmax(model_preds_probs, axis=1)
test_labels_encode = tf.argmax(test_label,axis=1)
model_result = calculate_accuracy_results(y_pred=model_preds,
                                           y_true=test_labels_encode)
print(model_result)

225/225 [==============================] - 2s 7ms/step
{'accuracy': 96.66759620747351, 'precision': 0.9681129255492303, 'recall': 0.966675962074735, 'f1': 0.9659454444517805}